services:
  web:
    image: 903322079825.dkr.ecr.ap-southeast-2.amazonaws.com/terraform-docker-demo:latest
    container_name: tf-docker-demo
    ports:
      - "80:8080"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/"]
      interval: 10s
      timeout: 3s
      retries: 5
